### ISSUE TITLE
GBS build failure

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer-ros#17]
Because of unpackaged files, below error occurs when building gbs.
* Link: https://build.tizen.org/package/live_build_log/devel:AIC:Tizen:5.0:nnsuite/nnstreamer-ros/standard/i586

```bash
[  119s] Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/abuild/rpmbuild/BUILDROOT/nnstreamer-ros-0.0.1-3.1.i386
[  119s] error: Installed (but unpackaged) file(s) found:
[  119s]    /usr/lib/gstreamer-1.0/libtensor_ros_src.so
```

**Comment by wooksong** [comment]
https://build.tizen.org/package/show/devel:AIC:Tizen:5.0:nnsuite/nnstreamer-ros

Resolved!
