### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer-ros#38]
We have potential clients who are using ROS2 right now.
(I will have meeting tomorrow and fetch their requirements.)

**Comment by wooksong** [comment]
@myungjoo How about branching out for ROS1?

- ros1 or ros distro name (Melodic?)
- main (for ros2)

**Comment by myungjoo** [comment]
Let's not branch out for ROS1 and ROS2.
I'd rather recommend to modularize (e.g., with euphemism: ros-common.c, ros1.c, and ros2.c) or to add #if #endif with build options.

**Comment by wooksong** [comment]
@myungjoo Got it. Since build scripts are not compatible with each other, the hierarchies of them would be complex to well organize them. But I understood what you meant.
